Repository Enkh-amir/The-Boys, pull requests merged in 2024-09, with the labels that each got.

#4 neesen
  G_T/index.js
Labels: bug, documentation

#7 log deer l gants ym hewellee
  team-se/Saruul.jsx
Labels: Test

#8 G_gerleeg_hasah
  G_T/index.js
  package-lock.json
Labels: bug

#9 T_dhiad_neg_log
  G_T/index.js
Labels: Test

#10 react_neesen
  project-gt/src/app/globals.css
  project-gt/src/app/page.js
Labels: Test

#11 filaa huvaasan
  G_T/project-front-end/.gitignore
  G_T/project-front-end/README.md
  G_T/project-front-end/jsconfig.json
  G_T/project-front-end/next.config.mjs
  G_T/project-front-end/package-lock.json
  G_T/project-front-end/package.json
  G_T/project-front-end/postcss.config.mjs
  G_T/project-front-end/src/app/favicon.ico
  G_T/project-front-end/src/app/fonts/GeistMonoVF.woff
  G_T/project-front-end/src/app/fonts/GeistVF.woff
  G_T/project-front-end/src/app/globals.css
  G_T/project-front-end/src/app/layout.js
  G_T/project-front-end/src/app/page.js
  G_T/project-front-end/tailwind.config.js
Labels: bug

#13 neesen
  G_T/project-back-end/server.js
Labels: bug

#15 Components-uusgev
  G_T/project-front-end/src/app/page.js
  G_T/project-front-end/src/app/page.jsx
  G_T/project-front-end/src/components/pages/LoginPage.jsx
  G_T/project-front-end/src/components/svg/Icon.jsx
Labels: Test

#18 yronhii ymaa hiisen
  G_T/project-back-end/.gitignore
  G_T/project-back-end/package-lock.json
  G_T/project-back-end/package.json
  G_T/project-back-end/server.js
Labels: Test

#19 test
  G_T/project-front-end/src/components/pages/LoginPage.jsx
  G_T/project-front-end/src/components/svg/Icon.jsx
  G_T/project-front-end/tailwind.config.js
Labels: bug

#23 Log-In-Page-duussan
  G_T/project-front-end/src/components/componont/ButtonBlue.jsx
  G_T/project-front-end/src/components/componont/Input.jsx
  G_T/project-front-end/src/components/componont/index.jsx
  G_T/project-front-end/src/components/pages/LoginPage.jsx
  G_T/project-front-end/src/components/svg/Icon.jsx
Labels: help wanted

#26 zasvar-2
  G_T/project-front-end/src/app/signinpage/page.jsx
  G_T/project-front-end/src/components/pages/LoginPage.jsx
Labels: bug
